---
substitutions:
  wifi_reboot_timeout: 15min

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: $wifi_reboot_timeout

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret wifi_ap_password

captive_portal:

sensor:
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s
