---
substitutions:
  friendly_name: ""
  comment: ""
  area: ""
  name_add_mac_suffix: "false"

esphome:
  name: $name
  friendly_name: $friendly_name
  comment: $comment
  area: $area
  name_add_mac_suffix: $name_add_mac_suffix

packages:
  preferences: !include common/preferences.yaml
  logger: !include common/logger.yaml
  api: !include common/api.yaml
  ota: !include common/ota.yaml
  time: !include common/time.yaml
  binary_sensors: !include common/binary_sensors.yaml
  sensors: !include common/sensors.yaml
  buttons: !include common/buttons.yaml
