---
substitutions:
  name: downstairs-lobby-presence
  friendly_name: Downstairs Lobby Presence Sensor
  area: Downstairs Lobby

packages:
  common: !include modules/devices/athom-presence-sensor.yaml
