---
substitutions:
  name: lab-server-rack-plug
  friendly_name: Lab Server Rack Plug
  room: Lab
  # Use this plug as a metering device
  restore_mode: ALWAYS_ON
  disabled_by_default: "true"

packages:
  common: !include modules/devices/athom-smart-plug-v2.yaml
