---
substitutions:
  name: laundry-motion-sensor
  friendly_name: Laundry Motion Sensor
  area: Laundry

packages:
  common: !include modules/devices/wemos-d1-mini.yaml

binary_sensor:
  - platform: gpio
    pin: GPIO0
    name: PIR
    device_class: motion
