---
substitutions:
  comment: Athom Smart Plug V2
  board: esp8285
  update_interval: 10s
  restore_mode: RESTORE_DEFAULT_OFF
  # Power bellow this threshold will be reported as 0W
  zero_power_threshold: "3"

packages:
  common: !include ../common-8266.yaml

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: 5
      mode:
        input: true
        pullup: true
      inverted: true
    name: Button
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.toggle: relay
      - timing:
          - ON for at least 4s
        then:
          - button.press: factory_reset_button

globals:
  - id: total_energy
    type: float
    restore_value: yes
    initial_value: "0.0"

sensor:
  - platform: cse7766
    current:
      name: Current
      filters:
        - throttle_average: ${update_interval}
    voltage:
      name: Voltage
      filters:
        - throttle_average: ${update_interval}
    power:
      name: Power
      id: power_sensor
      filters:
        - throttle_average: ${update_interval}
        - lambda: |-
            if (x < ${zero_power_threshold})
              return 0.0;
            else
              return x;
    energy:
      name: Energy
      id: energy_sensor
      unit_of_measurement: kWh
      filters:
        - throttle: ${update_interval}
        - multiply: 0.001 # Multiplication factor from W to kW is 0.001
      on_value:
        then:
          - lambda: |-
              static float previous_energy_value = 0.0;
              float current_energy_value = id(energy_sensor).state;
              id(total_energy) += current_energy_value - previous_energy_value;
              previous_energy_value = current_energy_value;
    apparent_power:
      name: Apparent Power
      filters:
        - throttle_average: ${update_interval}
    power_factor:
      name: Power Factor
      filters:
        - throttle_average: ${update_interval}

  - platform: total_daily_energy
    name: Total Daily Energy
    power_id: power_sensor
    unit_of_measurement: kWh
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001 # Multiplication factor from W to kW is 0.001

  - platform: template
    name: Total Energy
    unit_of_measurement: kWh
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    lambda: |-
      return id(total_energy);
    update_interval: ${update_interval}

switch:
  - platform: gpio
    name: Switch
    pin: GPIO12
    id: relay
    restore_mode: ${restore_mode}

light:
  - platform: status_led
    name: Status LED
    pin:
      number: GPIO13
      inverted: true
    entity_category: config
