---
substitutions:
  comment: NodeMCU 1.0 Dev Board
  board: nodemcuv2

packages:
  common: !include ../common-8266.yaml

esphome:
  project:
    name: NodeMCU.Dev Kit
    version: "1.0.0"

light:
  - platform: status_led
    name: Status LED
    pin:
      number: GPIO2
      inverted: true
    entity_category: config
