---
substitutions:
  comment: Sonoff S26
  board: esp01_1m
  restore_mode: RESTORE_DEFAULT_OFF
  disabled_by_default: "false"

packages:
  common: !include ../common-8266.yaml

esphome:
  project:
    name: "sonoff.s26"
    version: "1.0.0"

light:
  - platform: status_led
    name: Status LED
    pin:
      number: GPIO13
      inverted: true
    entity_category: config

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: Button
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - switch.toggle: relay_1
      - timing:
          - ON for at least 4s
        then:
          - button.press: factory_reset_button

switch:
  - platform: gpio
    name: Switch
    pin: GPIO12
    id: relay_1
    restore_mode: ${restore_mode}
    disabled_by_default: ${disabled_by_default}
