---
substitutions:
  comment: WeMos D1 Mini Dev Board

packages:
  common: !include ../common-8266.yaml

esphome:
  project:
    name: "WeMos.D1 Mini"
    version: "1.0.0"

light:
  - platform: status_led
    name: Status LED
    pin:
      number: GPIO2
      inverted: true
    entity_category: config
